name: Tip of the Day
description: Submit a new Tip-of-the-Day
labels: ["automated tip", "tip"]
assignees:
  - umlaeute
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a new Tip-of-the-Day.

        The Tips-of-the-Day will ultimately be displayed at Pd startup.
        This means, that any fancy markdown formatting will be lost.  It also means, that *only* GIF images are supported (even if GitHub let's you upload MP4-files, these will not be usable).

        Please fill out the form to create a new tip.  Once reviewed, it will be automatically included in the collection.

        (If you only have a vague idea about a missing tip, just file a [feature request](https://github.com/pd-externals/tipoftheday-plugin/issues/new) instead...)
  - type: textarea
    id: details
    attributes:
      label: Detail
      description: Longer (plain text) description of the tip.
      placeholder: |
        Most buggy Pd patches misbehave because the order-of-execution is ill-defined.

        Therefore, avoid connecting a single message outlet to multiple inlets.  Instead, use [trigger] so you get a defined order-of-execution.
      render: plain text
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: An (optional) link with additional information on the topic.
      placeholder: http://msp.ucsd.edu/Pd_documentation/x2.htm#s3.3
    validations:
      required: false
  - type: textarea
    id: image
    attributes:
      label: Image
      description: Optionally upload an image
      placeholder: |
        You can use this field to upload a single (animated) GIF.  All other content will be removed.
        GIFs should be smaller than 650x533.  Animated GIFs should have a constant framerate of 10fps.
        .
        Please note that only GIFs are supported.
    validations:
      required: false
