name: Tip of the Day
description: Request a new Tip-of-the-Day
title: "[Tip]: "
labels: ["automated tip", "tip"]
assignees:
  - umlaeute
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a new Tip-of-the-Day.
  - type: input
    id: filename
    attributes:
      label: Tip ID
      description: Suggested filename for the new tip (without path and extension). Leave empty if unsure.
      placeholder: new-tip
    validations:
      required: false
  - type: input
    id: title
    attributes:
      label: Title
      description: Short description of the tip 
      placeholder: Avoid fan-outs!
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Detail
      description: Longer (plain text) description of the tip.
      placeholder: |
        Most buggy Pd patches misbehave because the order-of-execution is ill-defined.

        Therefore, avoid connecting a single message outlet to multiple inlets.  Instead, use [trigger] so you get a defined order-of-execution.
      render: plain text
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: An (optional) link with additional information on the topic.
      placeholder: http://msp.ucsd.edu/Pd_documentation/x2.htm#s3.3
    validations:
      required: false
  - type: textarea
    id: image
    attributes:
      label: Image
      description: Optionally upload an image
      placeholder: |
        You can use this field to upload a single (animated) GIF.  All other content will be removed.
        .
        GIFs should be smaller than 650x533.  Animated GIFs should have a constant framerate of 10fps.
    validations:
      required: false
