name: PushGitlab

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Push To git.iem.at
      env: 
        token: ${{ secrets.GITLAB_TOKEN }}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "GitHub bridge"
        git config user.email "umlaeute@users.noreply.github.com"
        git remote set-url origin "https://oauth2:${token}@git.iem.at/pd/tipoftheday-plugin.git"
        git push origin main
